apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todoapp

resources:
  - namespace.yaml
  - serviceaccount-api.yaml
  - api-deployment.yaml
  - api-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

# Argo CD Image Updater rewrites these two newTag values on every new build.
images:
  - name: docker.io/kamleshcloud/todoapi
    newTag: latest
  - name: docker.io/kamleshcloud/todofrontend
    newTag: latest
